/*
 *Angus Henry
 * 09/03/2018
 * This programs caluculates the price of a meal
 * FormFastFoos.java
 */

package U2_A4_FastFood;
import java.text.DecimalFormat;
/**
 *
 * @author anhen3335
 */
public class FormFastFood extends javax.swing.JFrame {

    /**
     * Creates new form FormFastFood
     */
    public FormFastFood() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textBurgers = new javax.swing.JTextField();
        textFries = new javax.swing.JTextField();
        textDrinks = new javax.swing.JTextField();
        labelBeforeTax = new javax.swing.JLabel();
        labeltax = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        labelBurgers = new javax.swing.JLabel();
        labelFires = new javax.swing.JLabel();
        labelDrinks = new javax.swing.JLabel();
        labelTitle = new javax.swing.JLabel();
        buttonCalculate = new javax.swing.JButton();
        labelpayed = new javax.swing.JLabel();
        textPayed = new javax.swing.JTextField();
        labelChange = new javax.swing.JLabel();
        buttonCalculateChange = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textBurgers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBurgersActionPerformed(evt);
            }
        });

        textDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDrinksActionPerformed(evt);
            }
        });

        labelBeforeTax.setText("Total before taxs:");

        labeltax.setText("Tax:");

        labelTotal.setText("Final total:");

        labelBurgers.setText("# of Burgers");

        labelFires.setText("# of Fries");

        labelDrinks.setText("# of Drinks");

        labelTitle.setText("Meal price calculator");

        buttonCalculate.setText("Calculate");
        buttonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalculateActionPerformed(evt);
            }
        });

        labelpayed.setText("Enter the amount the customer payed");

        textPayed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPayedActionPerformed(evt);
            }
        });

        labelChange.setText("Change:");

        buttonCalculateChange.setText("Enter");
        buttonCalculateChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalculateChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelBurgers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelFires, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonCalculate)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labeltax)
                                    .addComponent(labelBeforeTax)
                                    .addComponent(labelTotal)))
                            .addComponent(textFries)
                            .addComponent(textBurgers)
                            .addComponent(textDrinks))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelpayed))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(textPayed, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonCalculateChange))
                                    .addComponent(labelChange)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelTitle)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBurgers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBurgers)
                    .addComponent(labelpayed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFires)
                    .addComponent(textPayed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCalculateChange))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDrinks)
                    .addComponent(labelChange))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBeforeTax)
                    .addComponent(buttonCalculate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labeltax)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTotal)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textBurgersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBurgersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBurgersActionPerformed

    private void textDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDrinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDrinksActionPerformed
    // Here we calculate the cost of the meal
    private void buttonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalculateActionPerformed
     double burgers,fries, softDrinks, totalTax, tax, finalTotal;
     burgers = 2.49 * Double.parseDouble (textBurgers.getText());
     fries = 1.89* Double.parseDouble (textFries.getText());
     softDrinks = 0.99 * Double.parseDouble (textDrinks.getText());
     totalTax = burgers + fries + softDrinks;
     tax = totalTax * 0.13;
     finalTotal = totalTax + tax;
     DecimalFormat x = new DecimalFormat ("###.##");
     labelBeforeTax.setText ("Total before taxes: " + x.format(totalTax) + "$");
     labeltax.setText ("Tax: " + x.format(tax) + "$");
     labelTotal.setText ("Total price " + x.format(finalTotal) + "$");
    }//GEN-LAST:event_buttonCalculateActionPerformed

    private void textPayedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPayedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPayedActionPerformed
    // Here we calculate the Change for teh customer
    private void buttonCalculateChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalculateChangeActionPerformed
        double burgers,fries, softDrinks, totalTax, tax, finalTotal, change, payed;
     burgers = 2.49 * Double.parseDouble (textBurgers.getText());
     fries = 1.89* Double.parseDouble (textFries.getText());
     softDrinks = 0.99 * Double.parseDouble (textDrinks.getText());
     totalTax = burgers + fries + softDrinks;
     tax = totalTax * 0.13;
     finalTotal = totalTax + tax;
     payed = Double.parseDouble (textPayed.getText());
     change = payed - finalTotal;
     DecimalFormat x = new DecimalFormat ("###.##");
     labelChange.setText ("Change: " + x.format(change) + "$");
     
        
    }//GEN-LAST:event_buttonCalculateChangeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFastFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFastFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFastFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFastFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFastFood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalculate;
    private javax.swing.JButton buttonCalculateChange;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelBeforeTax;
    private javax.swing.JLabel labelBurgers;
    private javax.swing.JLabel labelChange;
    private javax.swing.JLabel labelDrinks;
    private javax.swing.JLabel labelFires;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelpayed;
    private javax.swing.JLabel labeltax;
    private javax.swing.JTextField textBurgers;
    private javax.swing.JTextField textDrinks;
    private javax.swing.JTextField textFries;
    private javax.swing.JTextField textPayed;
    // End of variables declaration//GEN-END:variables
}
